---
- hosts: all
  tasks:
    - apt: name=apt-transport-https update_cache=yes state=present
      sudo: yes
    - apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=36A1D7869245C8950F966E92D8576A8BA88D21E9
      sudo: yes
    - command: sudo bash -c "echo deb https://get.docker.com/ubuntu docker main > /etc/apt/sources.list.d/docker.list"
      register: output
    - debug: var=output.stdout_lines
    - apt: name=lxc-docker update_cache=yes state=present
      sudo: yes
    - name: install pip
      apt: name=python-pip state=present
      sudo: yes
    - name: install docker-py
      pip: name=docker-py
      sudo: yes
    - name: create spark docker image
      docker_image: path="/vagrant/docker-setup" name="sudarshan/apache-spark" state=present
      sudo: yes
    - name: start spark master
      docker: image=sudarshan/apache-spark name=spark-master detach=True hostname=spark-master ports=8080:8080 state=running
      sudo: yes
