---
- hosts: all
  tasks:
    - apt: name=apt-transport-https update_cache=yes state=present
      sudo: yes
    - apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=36A1D7869245C8950F966E92D8576A8BA88D21E9
      sudo: yes
    - command: sudo bash -c "echo deb https://get.docker.com/ubuntu docker main > /etc/apt/sources.list.d/docker.list"
      register: output
    - debug: var=output.stdout_lines
    - apt: name=lxc-docker update_cache=yes state=present
      sudo: yes
